-- =============================================================================
-- ProArtist Africa — one-time Supabase setup for blog admin + public blog page
-- =============================================================================
-- Where: Supabase Dashboard → SQL Editor → New query → paste all → Run
-- Safe to re-run: uses IF NOT EXISTS / DROP POLICY IF EXISTS where possible
--
-- Still do manually in Dashboard (SQL cannot replace these):
--   1. Authentication → Users → Add user (email + password for admin login)
--   2. Confirm the user if email confirmation is enabled
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1) site_content — published page copy (blog, settings, etc.)
-- -----------------------------------------------------------------------------
create table if not exists public.site_content (
  section_key text primary key,
  title text,
  subtitle text,
  button_primary text,
  button_secondary text,
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

drop policy if exists "site_content_authenticated_all" on public.site_content;
create policy "site_content_authenticated_all"
on public.site_content
for all
to authenticated
using (true)
with check (true);

drop policy if exists "site_content_anon_read_blog" on public.site_content;
create policy "site_content_anon_read_blog"
on public.site_content
for select
to anon
using (section_key in ('blog', 'settings'));

grant select on table public.site_content to anon;
grant all on table public.site_content to authenticated;

-- -----------------------------------------------------------------------------
-- 2) blog_drafts — Save Draft workflow in admin.html
-- -----------------------------------------------------------------------------
create table if not exists public.blog_drafts (
  id uuid primary key default gen_random_uuid(),
  section_key text not null default 'blog',
  title text not null default 'Untitled draft',
  payload_json jsonb not null default '{}'::jsonb,
  status text not null default 'draft' check (status in ('draft', 'published')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists blog_drafts_section_updated_idx
on public.blog_drafts (section_key, updated_at desc);

alter table public.blog_drafts enable row level security;

drop policy if exists "blog_drafts_authenticated_all" on public.blog_drafts;
create policy "blog_drafts_authenticated_all"
on public.blog_drafts
for all
to authenticated
using (true)
with check (true);

grant all on table public.blog_drafts to authenticated;

-- -----------------------------------------------------------------------------
-- 3) Storage bucket blog-images (public read for preview-blog.html)
-- -----------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('blog-images', 'blog-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "blog_images_public_read" on storage.objects;
create policy "blog_images_public_read"
on storage.objects
for select
to anon
using (bucket_id = 'blog-images');

drop policy if exists "blog_images_authenticated_write" on storage.objects;
create policy "blog_images_authenticated_write"
on storage.objects
for all
to authenticated
using (bucket_id = 'blog-images')
with check (bucket_id = 'blog-images');

-- -----------------------------------------------------------------------------
-- 4) page_views — Analytics section in admin.html (optional but recommended)
-- -----------------------------------------------------------------------------
create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  page_path text not null,
  page_url text,
  referrer text,
  created_at timestamptz not null default now()
);

create index if not exists page_views_created_at_idx
on public.page_views (created_at desc);

create index if not exists page_views_page_path_idx
on public.page_views (page_path);

alter table public.page_views enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on table public.page_views to anon;
grant select, delete on table public.page_views to authenticated;

drop policy if exists "page_views_anon_insert" on public.page_views;
create policy "page_views_anon_insert"
on public.page_views
for insert
to anon
with check (true);

drop policy if exists "page_views_authenticated_read" on public.page_views;
create policy "page_views_authenticated_read"
on public.page_views
for select
to authenticated
using (true);

drop policy if exists "page_views_authenticated_delete" on public.page_views;
create policy "page_views_authenticated_delete"
on public.page_views
for delete
to authenticated
using (true);

-- -----------------------------------------------------------------------------
-- Done. Next steps (Dashboard only):
--   Authentication → Users → Add user → use that email/password on login.html
-- =============================================================================
