-- Page view tracking table for Analytics section in admin.html
-- Run this in Supabase SQL editor once.

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  page_path text not null,
  page_url text,
  referrer text,
  created_at timestamptz not null default now()
);

create index if not exists page_views_created_at_idx
on public.page_views(created_at desc);

create index if not exists page_views_page_path_idx
on public.page_views(page_path);

alter table public.page_views enable row level security;

grant usage on schema public to anon, authenticated;
grant insert on table public.page_views to anon;
grant select, delete on table public.page_views to authenticated;

drop policy if exists "page_views_anon_insert" on public.page_views;
create policy "page_views_anon_insert"
on public.page_views
for insert
to anon
with check (true);

drop policy if exists "page_views_authenticated_read" on public.page_views;
create policy "page_views_authenticated_read"
on public.page_views
for select
to authenticated
using (true);

drop policy if exists "page_views_authenticated_delete" on public.page_views;
create policy "page_views_authenticated_delete"
on public.page_views
for delete
to authenticated
using (true);
